### ISSUE TITLE
Login Page is loaded all over again

### ISSUE THREAD

**Issue by jevylein** [icecoder/ICEcoder#791] opened 2019-10-28 08:57 UTC
I downloaded Version 7, set a password and updated the settings to my preferences.
(editor theme eclipse, pugin sidebar on the right). After that A logged out and tried to log in again.

All it does, is loading the LogIn page all over again. The password is correct. There is nothing shown in the developper tools.

**Comment by smokeypell** [comment] 2019-11-20 23:02
I have the same issue. I have figured out what the issue is, but not how to fix it. Once you set your initial password, it is stored in the data/config_<user>_<domain>.php file as a hash.

`"password"	=> "\$2y\$10\$FkxnwsA0oGAsV7TVeQsfKOZPbvsMOuT.RiXzchx57QJTG2OGlCzca",`

When you hit the "Update" button in the settings menu for any reason, no matter if you change anything or not, the password field in this file is updated and the slashes"\" are stripped and whatever process in PHP can't properly read the hashed password without the dollar signs escaped.

`"password"	=> "$2y$10$FkxnwsA0oGAsV7TVeQsfKOZPbvsMOuT.RiXzchx57QJTG2OGlCzca",`
You can manually add backslashes before the dollar signs and save the file and you can log in again. But after any change in the settings menu, it strips the slashes again.

I have tried playing with the code a bit and haven't figured out how to get it to stop stripping the slashes.

**Comment by mattpass** [comment] 2020-02-01 13:53
@jevylein thanks for the issue raised (and sorry for delay in replying) and the finding @smokeypell - you were spot on re it stripping slashes. (ICEcoder moved to using BCrypt for its password hashing and that hashed password contains dollar characters - I didn't spot that the unescaping was removed when you update settings).

Have merged the PR from @smokeypell to fix this, plus implemented an extra tweak commit re setting the password in the first place.

Should be all sorted and working if you pull the latest code in this repo.

**Closed by mattpass** 2020-02-01 13:53 UTC
Labels: Bug, Version 7.1
