### ISSUE TITLE
IceCoder - Keeps adding code duplicates ( entire lines ) - Issue 714 , 715 related

### ISSUE THREAD

**Issue by marcoczen** [icecoder/ICEcoder#716] opened 2017-07-19 12:59 UTC
Matt,

With regards to issues 714, 715 - I thought the problem was related only to Firefox. I thought by switching to Chrome - this would go away.

But it did not. I had a buddy test my app recently and one entire section was brokenn because multiple lines of code were repeated ! THIS IS REALLY CRAZY.

Do you have another version that i can test out - You did say there was a line ending bug that was fixed somewhere ? ? I have setup the software / license the way i like it and so dont want to do a full reinstall. If i have to just replace the codemirror folder - I would like that.

p.s - Do i open this as a new issue or am I suppose to re-open the old issue ?

**Comment by mattpass** [comment] 2017-07-20 08:54
No, this issue wouldn't be browser dependant and if anything would be OS dependant as Windows and Linux have different line endings. The issue should be fixed from a commit made since v6.0 beta, so having the latest version from GitHub should work totally fine.

These are the 2 commits that should fix the issue:

https://github.com/mattpass/ICEcoder/commit/4bf04b1c082b2ea618057d00cef0f5728e024616
https://github.com/mattpass/ICEcoder/commit/0f971b547e129702bbf997a82e7b4da6dbc91d09

...but if you just grab the latest repo from GitHub that should have fixed it.

If an issue reoccurs you can either open a new issue or reopen the previous. The latter is probably best so I can re-read details re it.

**Comment by marcoczen** [comment] 2017-07-21 15:53
Ok Matt. 

1. OS Dependent ? It has happened in both Linux and Windows so far.
2. Do i need to do a reinstall or just overwrite file-control.php  from the 6.0 Beta from the repo here ?

**Comment by marcoczen** [comment] 2017-07-21 17:43
Tried that. Did not work. 
So i have to do a full copy ? 
The license file ? Anyway i can just copy them out ?

**Comment by marcoczen** [comment] 2017-08-01 16:10
Did a full reinstall. Copied out the license files named config-*.php in the lib folder and copied them back into the new install for the license and all the other settings.

After the reinstall, the issue of lines duplicating etc, seems to have been resolved. But will need to test more.

Unfortunately after the install- error msg -> file has changed outside of ICEcoder has popped up quite frequently.
Nuisance....

**Comment by mattpass** [comment] 2017-08-01 18:55
There are different line endings created by files created on Windows and Linux machines. eg \r\n on Windows, \r on Linux/Mac and \r\n on old Macs. The 2 commits mentioned handle those better across OS's.

Updating lib/file-control.php would have been just fine (sorry, have been away for a while).

Glad the issue has been sorted for you now. As for the issue of reporting the file has changed outside of ICEcoder, this is another OS dependant item I'm afraid, as Windows files have no modified datetime, but Linux files do.

The line in question is likely 265 of lib/file-control-xhr.php:

```
if (!(isset($_GET['fileMDT']))||$filemtime==$_GET['fileMDT']) {
```

You could try changing that to:

```
if (!(isset($_GET['fileMDT']))||$_GET['fileMDT']=="1000000"||$filemtime==$_GET['fileMDT']) {
````
That may solve the issue for you. Can you let me know if it does?

**Comment by marcoczen** [comment] 2017-08-08 09:13
Have patched. Will see if the message ( file has changed outside icecoder )  pops up again  ...

**Comment by marcoczen** [comment] 2017-08-10 05:30
@mattpass  - Sorry Matt. The message " ..file has changed outside .. " still popped ot. Have to exit icecoder and open again before making an edit that can be saved ....

**Comment by marcoczen** [comment] 2017-12-04 18:06
Updated in Issue #731 
Same problem - Entire row of lines being repeated - triggered when we delete blocks of code ....

**Comment by mattpass** [comment] 2017-12-08 08:43
Will see if I can reproduce and get to the bottom of this.

**Comment by mattpass** [comment] 2020-01-26 15:06
This was fixed a while ago so closing.

**Closed by mattpass** 2020-01-26 15:06 UTC
Labels: Bug
