### ISSUE TITLE
Sometimes, suddenly a line isn't editable any more

### ISSUE THREAD

**Issue by PM84** [icecoder/ICEcoder#687] opened 2017-03-10 23:51 UTC
Hallo,

sometimes, a line in the code isn't editable any more. Then I have to copy the line to an editor or word etc. edit the line and copy and paste it back to ICEcoder.  
The line won't be editable if I reload ICEcoder.

I use php 7 on an debian server

What can I do?

**Comment by mattpass** [comment] 2017-03-13 09:39
Do you have an older version of ICEcoder - is pre v6.0 beta as there was a problem with self closing tags (eg <img src="xyz.jpg">) causing the editor to freeze when you interact with them.

You could also open dev tools with F12, and then use ICEcoder. If the problem occurs, you may see error messages in the dev tools Console tab. These JS errors may help us pinpoint what the issue is.

Note you may need to open ICEcoders lib/config___settings.php file and change devMode from false to true and reload then try the above again. Reason being that the JS errors would refer to the minified ice-coder.min.js file until you turn devMode on, then it uses the regular ice-coder.js, so any error info will be more useful to debug in a non minified file.

**Comment by mattpass** [comment] 2019-08-12 23:26
Didn't hear back on this issue and is suspected it's resolved with the autoclose tag fix, so closing.

**Closed by mattpass** 2019-08-12 23:26 UTC
Labels: Bug
